name: Build and Deploy to Beta                                                                                                                      
                                                                                                                                                      
  on:                                                       
    push:
      branches: [beta]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4                                                                                                                 
          with:
            node-version: '20'                                                                                                                        
                                                            
        - run: npm install

        - run: npm run build

        - name: Deploy to GitHub Pages (beta)
          uses: peaceiris/actions-gh-pages@v3
          with:                                                                                                                                       
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist                                                                                                                       
            cname: diegoastein.github.io 
